name: Check & test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Quality & security checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make check

  test:
    name: Test & coverage
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run unit tests with coverage.
        run: |
          export GOPATH=$(go env GOPATH)
          make cover

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./resources/cover/cover.out